# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Stage 1: Build the application
FROM node:lts-alpine AS build

WORKDIR /app

# Copy package and install dependencies without running scripts
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts

# Copy source and build
COPY tsconfig.json ./
COPY src ./src
RUN npm run build

# Stage 2: Run the application
FROM node:lts-alpine

WORKDIR /app

# Copy app files and dependencies from build stage
COPY --from=build /app/package.json ./
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist

# Set environment
ENV NODE_ENV=production

# Start the MCP server
CMD ["node", "dist/index.js"]
